server:
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  boot:
    admin:
      client:
        url: http://localhost:8082

  datasource:
    url: jdbc:postgresql://localhost:5432/my-books
    username: my-books
    password: secret

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-2762279.okta.com/oauth2/default
          jwk-set-uri: https://dev-2762279.okta.com/oauth2/default/v1/keys
#          issuer-uri: https://accounts.google.com
#          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
security:
  oauth2:
    client:
      client-id: nicanor
      client-secret: 1234
      access-token-uri: http://localhost:8081/oauth/token
      grant-type: client_credentials

logging:
  level:
    liquibase: INFO

springdoc:
  api-docs:
    path: /api-src-doc
  swagger-ui:
    path: /api-doc
    oauth:
#      client-id: 635953397895-hkpkmjro2hrtp3as1k396vi44oqc9kll.apps.googleusercontent.com
      client-id: 0oahn9znOxaAtBDZk5d5
      use-pkce-with-authorization-code-grant: true

books:
  ribbon:
    eureka:
      enabled: false
    listOfServers: http://localhost:8081
user-books:
  ribbon:
    eureka:
      enabled: false
    listOfServers: http://localhost:8081