package higor.mybooks;

public class TestConstatns {
  public static final String  EXPECTED_BOOKS_PAGE = "{\n"
      + "   \"_embedded\":{\n"
      + "      \"books\":[\n"
      + "         {\n"
      + "            \"title\":\"Design Patterns com Java\",\n"
      + "            \"subtitle\":\"Projeto orientado a objetos guuado por padrões\",\n"
      + "            \"author\":\"Eduardo Guerra\",\n"
      + "            \"edition\":null,\n"
      + "            \"publisher\":\"Casa do Código\",\n"
      + "            \"pages\":274,\n"
      + "            \"isbn\":null,\n"
      + "            \"publishingDate\":null,\n"
      + "            \"_links\":{\n"
      + "               \"self\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/61\"\n"
      + "               },\n"
      + "               \"book\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/61\"\n"
      + "               },\n"
      + "               \"users\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/61/users\"\n"
      + "               },\n"
      + "               \"categories\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/61/categories\"\n"
      + "               }\n"
      + "            }\n"
      + "         },\n"
      + "         {\n"
      + "            \"title\":\"Reflexão e Anotações\",\n"
      + "            \"subtitle\":\"Componentes reutilizáveis em Java com\",\n"
      + "            \"author\":\"Eduardo Guerra\",\n"
      + "            \"edition\":null,\n"
      + "            \"publisher\":\"Casa do Código\",\n"
      + "            \"pages\":356,\n"
      + "            \"isbn\":null,\n"
      + "            \"publishingDate\":null,\n"
      + "            \"_links\":{\n"
      + "               \"self\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/62\"\n"
      + "               },\n"
      + "               \"book\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/62\"\n"
      + "               },\n"
      + "               \"users\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/62/users\"\n"
      + "               },\n"
      + "               \"categories\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/62/categories\"\n"
      + "               }\n"
      + "            }\n"
      + "         },\n"
      + "         {\n"
      + "            \"title\":\"Introduction to Neural Networks for Java\",\n"
      + "            \"subtitle\":\"An artificial neural networks aproach\",\n"
      + "            \"author\":\"Jeff Heaton\",\n"
      + "            \"edition\":null,\n"
      + "            \"publisher\":\"Heaton Research\",\n"
      + "            \"pages\":439,\n"
      + "            \"isbn\":null,\n"
      + "            \"publishingDate\":null,\n"
      + "            \"_links\":{\n"
      + "               \"self\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/63\"\n"
      + "               },\n"
      + "               \"book\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/63\"\n"
      + "               },\n"
      + "               \"users\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/63/users\"\n"
      + "               },\n"
      + "               \"categories\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/63/categories\"\n"
      + "               }\n"
      + "            }\n"
      + "         },\n"
      + "         {\n"
      + "            \"title\":\"Java 8 in Action\",\n"
      + "            \"subtitle\":\"Lambdas, streams, and functional-style programming\",\n"
      + "            \"author\":\"Raoul Gabriel Urma, Mario Fusco, Alan Mycroft\",\n"
      + "            \"edition\":null,\n"
      + "            \"publisher\":\"Manning\",\n"
      + "            \"pages\":479,\n"
      + "            \"isbn\":null,\n"
      + "            \"publishingDate\":null,\n"
      + "            \"_links\":{\n"
      + "               \"self\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/64\"\n"
      + "               },\n"
      + "               \"book\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/64\"\n"
      + "               },\n"
      + "               \"users\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/64/users\"\n"
      + "               },\n"
      + "               \"categories\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/64/categories\"\n"
      + "               }\n"
      + "            }\n"
      + "         },\n"
      + "         {\n"
      + "            \"title\":\"JSF e JPA\",\n"
      + "            \"subtitle\":\"Aplicações Java para web com\",\n"
      + "            \"author\":\"Gilliard Cordeiro\",\n"
      + "            \"edition\":null,\n"
      + "            \"publisher\":\"Casa do Código\",\n"
      + "            \"pages\":221,\n"
      + "            \"isbn\":null,\n"
      + "            \"publishingDate\":null,\n"
      + "            \"_links\":{\n"
      + "               \"self\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/65\"\n"
      + "               },\n"
      + "               \"book\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/65\"\n"
      + "               },\n"
      + "               \"users\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/65/users\"\n"
      + "               },\n"
      + "               \"categories\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/65/categories\"\n"
      + "               }\n"
      + "            }\n"
      + "         },\n"
      + "         {\n"
      + "            \"title\":\"As Conexões Ocultas\",\n"
      + "            \"subtitle\":\"Ciência para uma vida sustentável\",\n"
      + "            \"author\":\"Fritjof Capra\",\n"
      + "            \"edition\":null,\n"
      + "            \"publisher\":\"Cultrix\",\n"
      + "            \"pages\":296,\n"
      + "            \"isbn\":null,\n"
      + "            \"publishingDate\":null,\n"
      + "            \"_links\":{\n"
      + "               \"self\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/66\"\n"
      + "               },\n"
      + "               \"book\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/66\"\n"
      + "               },\n"
      + "               \"users\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/66/users\"\n"
      + "               },\n"
      + "               \"categories\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/66/categories\"\n"
      + "               }\n"
      + "            }\n"
      + "         },\n"
      + "         {\n"
      + "            \"title\":\"Inferno\",\n"
      + "            \"subtitle\":null,\n"
      + "            \"author\":\"Dan Brown\",\n"
      + "            \"edition\":null,\n"
      + "            \"publisher\":\"Arqueiro\",\n"
      + "            \"pages\":448,\n"
      + "            \"isbn\":null,\n"
      + "            \"publishingDate\":null,\n"
      + "            \"_links\":{\n"
      + "               \"self\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/67\"\n"
      + "               },\n"
      + "               \"book\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/67\"\n"
      + "               },\n"
      + "               \"users\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/67/users\"\n"
      + "               },\n"
      + "               \"categories\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/67/categories\"\n"
      + "               }\n"
      + "            }\n"
      + "         },\n"
      + "         {\n"
      + "            \"title\":\"O Pequeno Príncipe\",\n"
      + "            \"subtitle\":null,\n"
      + "            \"author\":\"Antoine de Saint-Exupéry\",\n"
      + "            \"edition\":null,\n"
      + "            \"publisher\":\"Reynal and Hitchcock, Gallimard\",\n"
      + "            \"pages\":94,\n"
      + "            \"isbn\":null,\n"
      + "            \"publishingDate\":null,\n"
      + "            \"_links\":{\n"
      + "               \"self\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/68\"\n"
      + "               },\n"
      + "               \"book\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/68\"\n"
      + "               },\n"
      + "               \"users\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/68/users\"\n"
      + "               },\n"
      + "               \"categories\":{\n"
      + "                  \"href\":\"http://localhost:8081/v1/books/68/categories\"\n"
      + "               }\n"
      + "            }\n"
      + "         }\n"
      + "      ]\n"
      + "   },\n"
      + "   \"_links\":{\n"
      + "      \"self\":{\n"
      + "         \"href\":\"http://localhost:8081/v1/books\"\n"
      + "      },\n"
      + "      \"profile\":{\n"
      + "         \"href\":\"http://localhost:8081/v1/profile/books\"\n"
      + "      },\n"
      + "      \"search\":{\n"
      + "         \"href\":\"http://localhost:8081/v1/books/search\"\n"
      + "      }\n"
      + "   },\n"
      + "   \"page\":{\n"
      + "      \"size\":10,\n"
      + "      \"totalElements\":8,\n"
      + "      \"totalPages\":1,\n"
      + "      \"number\":0\n"
      + "   }\n"
      + "}";

  public static final String EXPECTED_USER_BY_EMAIL = "{\n"
      + "  \"name\": null,\n"
      + "  \"surname\": null,\n"
      + "  \"email\": \"nicanor@mybooks.com\",\n"
      + "  \"_links\": {\n"
      + "    \"self\": {\n"
      + "      \"href\": \"http://localhost:8081/v1/users/3\"\n"
      + "    },\n"
      + "    \"user\": {\n"
      + "      \"href\": \"http://localhost:8081/v1/users/3\"\n"
      + "    },\n"
      + "    \"books\": {\n"
      + "      \"href\": \"http://localhost:8081/v1/users/3/books\"\n"
      + "    }\n"
      + "  }\n"
      + "}";
}
